### ISSUE TITLE
合成木材的問題

### ISSUE THREAD

**Issue by james10120** [bigrice1018/AnotherWayToStart#1]
在合成表上面所有木頭都可以轉成一般的木頭，但是我要合成木材的話，就必須要用原版的合成桌在按旁邊的箭頭，這樣我就沒辦法一次製造一組木材，而且也必須要用原版合成桌，不知道這有沒有辦法修改?或這是你故意要這樣設計?

**Comment by bigrice1018** [comment]
This is a problem from my script which will be fix in Thx next version.
For now you can just shift click down the logs from the crafting grid
Hope you enjoy AWTS
