### ISSUE TITLE
使用tinker io的物品 crash

### ISSUE THREAD

**Issue by InterfaceGUI** [bigrice1018/AnotherWayToStart#11]
我有刪減一些模組(MEK,家具,..)合成表也有移除,應該無關八..
崩潰後,ImmersiveEngineering 的水車整個亂掉
![2016-09-18_10 57 27](https://cloud.githubusercontent.com/assets/15845368/18612621/84853286-7d91-11e6-9d26-c7c44c344fb7.png)

崩潰報告:(多次使用tinker IO 的崩潰,不同時段)正確來講,應該是放了燃料輸入機才這樣

[crash-2016-09-18_10.29.53-client.txt](https://github.com/bigrice1018/AnotherWayToStart/files/478503/crash-2016-09-18_10.29.53-client.txt)
[crash-2016-09-18_11.06.18-client.txt](https://github.com/bigrice1018/AnotherWayToStart/files/478504/crash-2016-09-18_11.06.18-client.txt)

**Comment by bigrice1018** [comment]
先把 Optifine 删除
Optifine 可能就是原凶

**Comment by InterfaceGUI** [comment]
Optifine刪掉讓我有點煎熬...
我就先試試看,謝謝

**Comment by bigrice1018** [comment]
我明白....
你看可看看這個
https://forum.feed-the-beast.com/threads/guide-how-to-run-infinity-evolved-with-1-0gb-ram-allocation.149222/

**Comment by InterfaceGUI** [comment]
我式過後, OptiFine_D6 的不會 ,但是D4的就會像上面一樣crash,額且是不定時...
OK,解決了謝謝

**Comment by bigrice1018** [comment]
不客氣~
