### ISSUE TITLE
 伺服器自動CRASH

### ISSUE THREAD

**Issue by Threeyearsmio** [bigrice1018/AnotherWayToStart#12]
[crash-2016-10-05_14.14.20-server.txt](https://github.com/bigrice1018/AnotherWayToStart/files/510213/crash-2016-10-05_14.14.20-server.txt)
這是崩潰報告 每次都是跑到某些特定的地方就會CRASH 一登入又跳掉了
每次都是叫回備份檔案 但是跑到同地方又跳了
希望有辦法能解決 謝謝

**Comment by bigrice1018** [comment]
請問可以給client的crash report?

**Comment by Threeyearsmio** [comment]
單人端沒有相對應的CRASH REPORT 就只是跳出server close的字樣 並回到主畫面
還有新開平地世界測試東西的時候 發現進入deep dark時也會crash

**Comment by bigrice1018** [comment]
AWTS 版本是最新嗎?

**Comment by bigrice1018** [comment]
AWTS 版本是最新嗎?
最新版本是1.2.8

**Comment by Threeyearsmio** [comment]
是的 單人端跟伺服端都是1.2.8

**Comment by bigrice1018** [comment]
抱歉太晚回你，回家之後忘記了._.
這個由於模組BUG造成的問題
只可以先不要去會讓你CRASH的地方

DEEP DARK的話可以嘗試去删走DEEP DARK世界後再看看

**Comment by Threeyearsmio** [comment]
好的 希望之後有辦法能解決這問題~
畢竟不能跑圖的話 會少了很多事情做ww
