### ISSUE TITLE
Nether Quartz not generating

### ISSUE THREAD

**Issue by Branden6474** [bigrice1018/AnotherWayToStart#13]
I've been having a lot of trouble trying to get nether quartz to actually generate in the nether atm the only place I can find it is by bee hives.

**Comment by bigrice1018** [comment]
There is nether quartz in the nether...
But very few and rare
You can use digital miner to find it

Here is a fix for you~
Drop and override the file into "config\cofh\world"
Also, Change the file type from ".txt" to ".json"
[MC-Nether.txt](https://github.com/bigrice1018/AnotherWayToStart/files/560051/MC-Nether.txt)
