### ISSUE TITLE
ThaumicTinkerer 的 Bedrock dimension 生成問題

### ISSUE THREAD

**Issue by waitLH** [bigrice1018/AnotherWayToStart#14]
Bedrock dimension 的y261-265位置全部都是沙子，但原本應該都是基岩才對，由於頂部全是沙子會導致那裡的礦物挖掘非常麻煩，我連續嘗試了幾個存檔都是一樣，刪除世界重新加載還是沙子

**Comment by bigrice1018** [comment]
這是正常的 全部模組包都是這樣 
我們是沒有修改過的
