### ISSUE TITLE
关于多人NEI问题

### ISSUE THREAD

**Issue by zxc136360** [bigrice1018/AnotherWayToStart#18]
多人服务器的时候nei查不到botania的任何功能花。好像还有其他的物品也查不到

**Comment by zxc136360** [comment]
还有地狱的地狱石英生成太少了吧。。用数字采矿机最大范围才100+石英。 是特性吗。。

**Comment by bigrice1018** [comment]
NEI 的問題你可以去看單人的config裏的inpurecore去設定

Nether quartz就不會增多啦
