### ISSUE TITLE
合成表Steel Fence問題

### ISSUE THREAD

**Issue by james10120** [bigrice1018/AnotherWayToStart#2]
因為合成許多東西時必須要用到Immersive Engineering模組的MetalPress，那我在製作時就必須要有Steel Rod，但Steel Rod只有MetalPress能夠製作...

另一個小問題就是more planets 模組的slime不斷無視亮度的在我家出生.....他的啪啪聲真的很噁心...

**Comment by bigrice1018** [comment]
第一個問題
![image](https://cloud.githubusercontent.com/assets/13717190/15273532/2e6b0594-1acf-11e6-93a3-8066c11c2270.png)
Steel Rod 有合成表阿...

第二個問題己在下個版本解決(1.2.2)

**Comment by james10120** [comment]
![immer](https://cloud.githubusercontent.com/assets/5953424/15273646/2a3ffffc-1ad3-11e6-800a-f818c67567ec.png)

**Comment by james10120** [comment]
我是用Server
![immer](https://cloud.githubusercontent.com/assets/5953424/15273652/3b768566-1ad3-11e6-9dc7-115fcab2bcab.png)

**Comment by bigrice1018** [comment]
把原本的scripts删走
重新放下去
