### ISSUE TITLE
死掉後會Crash

### ISSUE THREAD

**Issue by james10120** [bigrice1018/AnotherWayToStart#5]
不好意思我又來了，更新1.2.2.1後，死後會Crash，在上線後也找不到墳墓，伺服器和單人都有發生問題。

**Comment by bigrice1018** [comment]
請提供Crash Report和Log檔

**Comment by bigrice1018** [comment]
不需要了
我正在找方法FIX

先使用指令把身上的東西拿回來吧
/ob_inventory restore

**Comment by james10120** [comment]
辛苦了大米大大，我就暫時把它當成另類的極限來玩了

**Comment by bigrice1018** [comment]
找到方法了...

先把witchery删走吧
