### ISSUE TITLE
Automagy Redcrystal stacking 

### ISSUE THREAD

**Issue by james10120** [bigrice1018/AnotherWayToStart#6]
因為我不太清楚是甚麼模組，也沒有找到可以調整控制的地方，
現在是使用右鍵對地板就能放東西在地板上，但是當我想要用
automagy的紅石時候，就會變成像把ingot放在地板一樣的情況..
不知道有地方可以調整嗎?

**Comment by bigrice1018** [comment]
那個模組是可以自定義的
請提供一下物品名稱~

**Comment by james10120** [comment]
Redcrystal

**Comment by bigrice1018** [comment]
你需要馬上修嗎?
你要的話我吧檔案給你~

**Comment by james10120** [comment]
不用沒關係，謝謝你
我已經用一般的紅石完成了

**Comment by bigrice1018** [comment]
下個版本會修正~
Fix in next version 
"Automagy Redcrystal stacking"
