### ISSUE TITLE
不知名的Crash

### ISSUE THREAD

**Issue by Goodre4m** [bigrice1018/AnotherWayToStart#7]
有时可以进入到游戏，貌似是加载到某些方块就Crash了。
第一次开一个世界，玩着玩着，掉到一个峡谷里面，炸了。
另外开了一个世界，直接就Crash了。

**Comment by Goodream24** [comment]
[Uploading crash-2016-07-03_03.32.55-server.txt…]()

**Comment by Goodre4m** [comment]
[crash-2016-07-03_03.32.55-server.txt](https://github.com/bigrice1018/AnotherWayToStart/files/344719/crash-2016-07-03_03.32.55-server.txt)
[fml-client-1 - 副本.txt](https://github.com/bigrice1018/AnotherWayToStart/files/344724/fml-client-1.-.txt)
[latest - 副本.txt](https://github.com/bigrice1018/AnotherWayToStart/files/344726/latest.-.txt)

第二个txt由于太大了，传不上来，所以删掉前面大部分应该没用的信息了。

**Comment by bigrice1018** [comment]
Ram 不足夠
建議4G 至少3G~

**Comment by Goodre4m** [comment]
设置了4G还是Crash……

**Comment by bigrice1018** [comment]
Fixed in next update
